language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: "python setup.py -q install"

script:
  # command to run tests
  - "python setup.py -q test"
  # build documentation
  - "pip install Sphinx"
  - "sphinx-build -nW -c docs/ -b html docs docs/_build/html"
