language: python

addons:
  postgresql: "9.3"

# command to install dependencies
install:
  - pip install -q -e .[postgresql]

before_script:
  - cp .development.ini.travis development.ini
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  # command to run tests
  - python setup.py test -a "-e ${TOXENV}"

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=behave
  - TOXENV=py2-docs
  - TOXENV=py3-docs

# TODO: http://docs.travis-ci.com/user/speeding-up-the-build/
